apiVersion: v1
kind: Service
metadata:
  name: convertcurrencyservice
  annotations:
    konghq.com/plugins: rate-limiting-2
    kubernetes.io/ingress.class: kong
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: convertcurrencyservice
  type: NodePort  
  ports:
  - port: 8081
    nodePort: 30080