apiVersion: v1
kind: Service
metadata:
  name: convertcurrencyservice
  annotations:
    konghq.com/plugins: rate-limiting-2
spec:
  selector:
    app: convertcurrencyservice
  type: NodePort  
  ports:
  - port: 8081
    nodePort: 30080