spring.application.name: conversionfactor
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver 
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    config:
      enabled: false    
      
management.endpoints.web.exposure.include: '*'


        
    
       